[project]
name = "mcp-trend-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.24.0",
    "mcp[cli]>=1.0.0",
    "pydantic>=2.0.0",
]
